name: Block PRs to Master

on:
  pull_request:
    branches:
      - master

jobs:
  block:
    runs-on: ubuntu-latest

    steps:
      - name: Comment and close PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Pull Requests para master não são permitidos. Utilize a branch develop.'
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'closed'
            });